### ISSUE TITLE
Wedge configurationa not working

### ISSUE THREAD

**Issue by gregadzrodz** [krajit/dynamicRefine2DFvMesh#1]
I ran your damBreak tutorial and it works. I then transformed it to a wedge geometry and it crashes at the first refinement giving the following error:
  
`PIMPLE: iteration 1
Selected 24 cells for refinement out of 2268.

--> FOAM FATAL ERROR: 
cell 580 of level 0 does not seem to have 8 points of equal or lower level
cellPoints:8(2916 2917 587 588 2958 2959 629 630)
pointLevels:8{0}

    From function hexRef2D::setRefinement(const labelList&, polyTopoChange&)
    in file hexRef2D/hexRef2D.C at line 3568.

FOAM aborting

#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::error::abort() at ??:?
#2  Foam::hexRef2D::setRefinement(Foam::List<int> const&, Foam::polyTopoChange&) at ??:?
#3  Foam::dynamicRefine2DFvMesh::refine(Foam::List<int> const&) at ??:?
#4  Foam::dynamicRefine2DFvMesh::update() at ??:?
#5  ? at ??:?
#6  __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
#7  ? at ??:?
Aborted`

Mind you, Lucas code works withe wedges.

**Comment by krajit** [comment]
Hi, Thanks for checking it out. I did not need wedge cells in my mesh so I did not try.
